default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: children_supervisor_database_development

test:
  <<: *default
  database: children_supervisor_database_test

production:
  <<: *default
  database: children_supervisor_database_production
